### ISSUE TITLE
No TypeString for HM-LC-Sw1-Pl-2 returned

### ISSUE THREAD

**Issue by wbuh** [Homegear/HomegearLib.NET#3]
For a HM-LC-Sw1-Pl-2 device homegear.net seems to return an empty TypeString value.
In Homegear CLI the value is present.

**Comment by hfedcba** [comment]
Could you execute a "listDevices" with PHP and tell me, if the type string is present there?

**Comment by wbuh** [comment]
homegear.NET Version 0.1.4.3 in combination with Homegear >= 0.6.0-965 solved the problem.

**Comment by wbuh** [comment]
Error is still there, sorry.
listDevices with PHP showed all learned devices.
The type string is present in the output for all devices.
I can see the type string of every device if I execute the "ls" command via homegear cli in putty, too.

Problem appears to happen with all new devices learned via .NET dll.

Snippet from listDevices of an affected device:
[30] => Array
        (
            [ADDRESS] => JExxxxxxx6:1
            [AES_ACTIVE] => 0
            [CHANNEL] => 1
            [DIRECTION] => 1
            [FAMILY] => 0
            [FLAGS] => 1
            [ID] => 9
            [INDEX] => 1
            [LINK_SOURCE_ROLES] => WEATHER_TH
            [LINK_TARGET_ROLES] =>
            [PARAMSETS] => Array
                (
                    [0] => MASTER
                    [1] => VALUES
                    [2] => LINK
                )

```
        [PARENT] => JEQ0121626
        [PARENT_TYPE] => HM-CC-TC
        [TYPE] => WEATHER
        [VERSION] => 15
    )
```

**Comment by hfedcba** [comment]
It should work in 0.1.4.4?

**Comment by wbuh** [comment]
Yep! After connecting it seemed nothing changed. After executing a Reload() the type strings appeared.
So perfect! Thanks!

**Comment by wbuh** [comment]
Mhhmmm. Cheered too soon.
After learning a new device: type string appears.
Changing a property like "Interface" or name of an other device: type string disappears.
Executing a Reload: type string reappers.

Only those devices are affected, that has been learned via the .NET dll.
The oldest ones which were learned by the eq3 tool present their typestring everytime.
Strange.

**Comment by hfedcba** [comment]
> The oldest ones which were learned by the eq3 tool present their typestring everytime.

That is odd... The eQ3 tool executes the same RPC methods as the lib. There is absolutely no difference.

Could you check, if the error also occurs with the test application?

**Comment by wbuh** [comment]
Maybe another hint:
after a reboot of the Raspi all devices appear at every time / refresh.

Another problem (maybe same cause): those learned devices are unkown to openHAB.
In the OpenHAB error log appears
2015-06-26 13:21:21.399 [WARN ] [.b.h.i.c.HomematicCommunicator] - Can't find DatapointConfig[address=JXXxxxxxx,channel=1,parameter=LEVEL], value is not published to openHAB!

A reboot fixes this problem, too.
Is there some kind of database, which needs to be updated?

**Comment by hfedcba** [comment]
ok, found the error ;-). Your hint helped. It is fixed in Homegear 0.6.0-967.

**Comment by wbuh** [comment]
Upgraded to the latest homegear 0.6.0, but issue is still there, sorry.

**Comment by hfedcba** [comment]
No, it should work now. Just tested it again:
- Enabled pairing mode in HomegearLibTest
- Paired a new device (HM-RC-Key4-2)
- Type String is there
- Changed interface: Type String is still there
- Reload of HomegearLibTest: Type String there
- Restart of Homegear: Type String there

Are you sure, you updated to at least 0.6.0-967? Building takes some time, so it is possible 0.6.0-966 was still online? Did you check if it works with HomegearLibTest?
